# Generated by Django 5.0.2 on 2024-03-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
